# Generated by Django 2.2.6 on 2019-12-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profiles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='location',
            field=models.CharField(default='my location default', max_length=120),
        ),
    ]
