# Generated by Django 2.2.6 on 2019-12-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profiles_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='location',
            field=models.CharField(blank=True, default='my location default', max_length=120, null=True),
        ),
    ]
