# Generated by Django 2.2.6 on 2019-12-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20191219_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='job',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='location',
        ),
    ]
